name: CI

on:
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Copy env Vars
        run: cp example.env .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Test Container
        run: docker compose build test

      - name: Run Tests
        run: docker compose run test rspec

      - name: Run Rubocop
        run: docker compose run test rubocop --fail-level=error
        continue-on-error: false

      - name: Tear Down Containers
        run: docker compose down